# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yug7PLcKTmdK_63gs7HF9D5XVfM_V1kt
"""

!pip install streamlit
import streamlit
import sklearn # Use sklearn instead of scikit-learn
import numpy

# Now you can use functions and classes from these libraries
# For example:
streamlit.title("My Streamlit App")